#!/bin/sh
#Set new wallpaper from Unsplash and run wal

#wget https://source.unsplash.com/random/ -O ~/Pictures/wallpapers/unsplash.png
#wget https://source.unsplash.com/random/1920x1080 -O ~/Pictures/wallpapers/unsplash.png
#rm ~/.cache/wal/schemes/*
wal -c

RAND=$(od -An -N1 -i /dev/random)
RAND=$(echo "$RAND % 2" | bc)
if [ $RAND -eq 0 ]
then
    randsplash
else
    randart
fi

case "$1" in
    -u|--unsplash)
        randsplash
    ;;

    -a|--artstation)
        randart
    ;;
esac

PIC=~/Pictures/wallpapers/current/current.png

case "$1" in
    
    -d|--dark)
        wal -i $PIC --saturate 0.6
    ;;
    
    -l|--light)
        wal -i $PIC -l --saturate 0.6
    ;;

    *)    
    RAND=$(od -An -N1 -i /dev/random)
    RAND=$(echo "$RAND % 2" | bc)
    if [ $RAND -eq 0 ]
    then
    #    echo "Bye"
        wal -i $PIC -l --saturate 0.6
    else
    #    echo "Hello"
        wal -i $PIC --saturate 0.6
    fi
    ;;
esac

xrdb $HOME/.cache/wal/colors.Xresources

#Spicetify
spicetify update

#Zathura
genzathurarc

#Steam
wal-steam -w

i3-msg reload

rm $HOME/.cache/thumbnails/neofetch/*
neofetch --gtk3 off
